### ISSUE TITLE
strange read failure - related to total enclosed filename length

### ISSUE THREAD

**Issue by johnjansen** [pablotron/zip-crystal#1]
[jnl 26.zip](https://github.com/pablotron/zip-crystal/files/514082/jnl.26.zip)

Attempting to read the attached file results in a `couldn't read full CDR entry (9 != 46) (Zip::Error)` however removing a single char from the filename of any file at the deepest level results in a successful read. I have removed all the content from the files which hasnt changed the outcome.

Creating a new structure with all same elements, including a copy of the EVERY file works ....

It seems like in this case, when the combined total characters in the filenames at the lowest level hits 700 the archive is unreadable (although i strongly suspect this is a very strange coincidence)

This problem also seems to have something to do the the precise archives im having to read ... NOTE other extractors can extract without issue

**Comment by pablotron** [comment]
Hi John,

Can you tell me what version of Crystal you are using?

Thanks,

**Comment by johnjansen** [comment]
Crystal 0.19.3 (2016-09-30)

**Comment by pablotron** [comment]
Hi John,

I can see the same behavior here.  I have a hunch about what is
happening, but I won't have time to investigate further until tomorrow
evening.

Thanks,
- John Jansen (notifications@github.com) wrote:
  >    Crystal 0.19.3 (2016-09-30)
  > 
  >    -
  >    You are receiving this because you commented.
  >    Reply to this email directly, view it on GitHub, or mute the thread.
  > 
  >    Link:
  >    https://github.com/pablotron/zip-crystal/issues/1#issuecomment-252006229

## 

Paul Duncan pabs@pablotron.org        OpenPGP Key ID: 0x82C29562
http://pablotron.org/                   http://paulduncan.org/

**Comment by johnjansen** [comment]
no problem, its pretty damn weird ...

**Comment by johnjansen** [comment]
any thoughts on this @pablotron

**Comment by pablotron** [comment]
Sorry, I've had a hectic week.  I'll spend some time on it now.

**Comment by pablotron** [comment]
The zip file has some odd data in the CDR entry for the last file in the archive.  The data is located right after the path length, comment length, and extras length, but before the beginning of the path data.

Specifically, the bytes between < and > in the dump below:

```
00015810  50 4b 01 02 15 03 14 00  08 00 08 00 08 a1 45 49  |PK............EI|
00015820  b7 bb d6 53 64 00 00 00  b2 00 00 00 0e 00 0c 00  |...Sd...........|
00015830  00 00<00 00 00 00 00 40  80 81 a1 37 01 00>5f 5f  |.......@...7..__|
00015840  4d 41 43 4f 53 58 2f 2e  5f 6a 6e 6c 55 58 08 00  |MACOSX/._jnlUX..|
00015850  8b c0 f5 57 1f c0 f5 57  50 4b 05 06 00 00 00 00  |...W...WPK......|
00015860  59 00 59 00 07 20 00 00  51 38 01 00 00 00        |Y.Y.. ..Q8....|
```

Since other tools can open this archive just fine, it is probably being caused by a flag from in the spec that I am not supporting.

I will investigate further and let you know.

**Comment by pablotron** [comment]
Nope, that data checks out.  But I'm close, stay tuned :).

**Comment by pablotron** [comment]
Crystal appears to be reading garbage for the last 7 bytes of the extras block:

```
entry = 88, io.pos = 88080
path_len = 14, extras_len = 12, comment_len = 0, data_len = 26
data_buf = 5f,5f,4d,41,43,4f,53,58,2f,2e,5f,6a,6e,6c,55,58,8,0,8b,0,0,0,0,0,0,0
```

Versus the actual file contents:

```
00015840  4d 41 43 4f 53 58 2f 2e  5f 6a 6e 6c 55 58 08 00  |MACOSX/._jnlUX..|
00015850  8b<c0 f5 57 1f c0 f5 57> 50 4b 05 06 00 00 00 00  |...W...WPK......|
```

The bytes before < are being read correctly, and the bytes between < and > are in the file, but are somehow being truncated.

**Comment by johnjansen** [comment]
you should create an issue over at crystal-lang if that is the case :-)

**Comment by pablotron** [comment]
Hi John, 

I switched from using `IO#read` to `IO#read_fully`, which resolved the truncated reads issue.  The sample `jnl.zip` you provided reads correctly for me now.

Version 0.1.2 includes this fix.

Thanks again, and sorry for the trouble.
